- hosts: localhost
  vars:
    greeting: Hello world! 
    region :
            - usa
            - europe
            - asia
  vars_files:
              - /home/cloudshell-user/course/var/my_external_var
  tasks:
    - name: Ansible Basic Variable Example
      debug:
          msg: "{{ region_file [0] }}"
